apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    version: "0.73.1"
    releaseName: my-jaeger
    namespace: jaeger2
    #valuesFile: my-values.yaml
    valuesInline:
      provisionDataStore:
        cassandra: false
      allInOne:
        enabled: true
      storage:
        type: none
      agent:
        enabled: false
      collector:
        enabled: false
      query:
        enabled: false
